# Generated by Django 4.1.1 on 2022-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(max_length=15, unique=True, verbose_name="핸드폰 번호"),
        ),
    ]
