# Generated by Django 4.1.1 on 2022-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_state",
            field=models.BooleanField(default=True),
        ),
    ]
