# Generated by Django 4.1.1 on 2022-09-14 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_rename_name_product_title"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="thumbnail",
            table="thumbnails",
        ),
        migrations.CreateModel(
            name="UserProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ManyToManyField(
                through="products.UserProduct", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
